spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - name: HttpRequestCounter
              args:
               instanceTag: "uri.toString()"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true

server:
  port: 11000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:12345/eureka
